### ISSUE TITLE
Test receiver with spurious bytes

### ISSUE THREAD

**Issue by StefanoSperetta** [DelfiSpace/HPI_FlightSoftware#2]
Test to see if the receiver can recover from a wrong packet received

**Comment by StefanoSperetta** [comment]
This test is probably hard to perform as it requires modifying the java code to transmit incorrect frames on the bus...

**Comment by StefanoSperetta** [comment]
@MFvandenBos , how did the test go?

**Comment by MFvandenBos** [comment]
At first there seemed to be no problems, 

However this afternoon I extended the test a bit further and it does not succeed. 

Odd thing: the value of the byte matters: if i send raw bytes with values above 127 it causes problems.  
above 127 it is converted in a negative value by the code, so I tried and indeed negative values cause issues. If the spurious bytes are no longer being sent, or the bytes are no longer negative the system does recover. 

Also when I am sending random byte arrays the test also fails. But the randomizer had a very large chance to go over 127.

**Comment by StefanoSperetta** [comment]
My fault, the idea of transmitting directly to the COM port has a big flaw: the protocol to the EGSE duplicates the bytes in order to send "extra" information (like the address bit). So, per each byte sent, you are supposed to send 2 bytes to the COM port.

Considering the byte that you want to send, you should send it in this way (assuming the value is contained in the data variable):

out.write( FIRST_BYTE | STOP_TRANSMISSION | (data >> 7) & 0x01 );
out.write( data & 0x7F );
out.flush();

**Comment by MFvandenBos** [comment]
I am getting an error on send(frame) ( I think it is the same on both implementations of PCInterface. )

I am calling pcInterface.send(frame); with frame: 
PQ9 frame = new PQ9(2, 1, new byte[]{17, 1});

Exception in thread "Thread-0" working
java.lang.NullPointerException
	at org.delfispace.protocols.pq9.RS485PCInterface.init(RS485PCInterface.java:49)
	at org.delfispace.protocols.pq9.PCInterface$readerThread.run(PCInterface.java:163)
Exception in thread "main" java.lang.NullPointerException
	at org.delfispace.protocols.pq9.RS485PCInterface.send(RS485PCInterface.java:159)
	at org.delfispace.pq9functionaltests.performanceTests.TestHPI.send(TestHPI.java:65)
	at org.delfispace.pq9functionaltests.performanceTests.TestHPI.main(TestHPI.java:94) 

I do not understand what is wrong, it seems to me the same function is used by the GUI.

**Comment by StefanoSperetta** [comment]
Trying to replicate the issue but I cannot compile the PQ9FunctionalTests project on my machine.
Is the serial port correct (COM12)?
Can you maybe try putting a delay (1s or similar) after the System.out.println("working")?  Problem might be because the send comes before the initialization is completed but I do not think it is possible... Main fear is that the serial port object is null....

**Comment by MFvandenBos** [comment]
There must have been something blocking the comPort yesterday. Since today it is working, and the only thing I added was a check if the comPort is not null.

**Comment by MFvandenBos** [comment]
For the byte arrays I have tested the system always recovers. there are a few bytes that cause the HPI to miss several pings, but most I have seen it miss is about 8 pings in a row

**Comment by StefanoSperetta** [comment]
Sounds good, I think we can close the issue at this stage.
