### ISSUE TITLE
EPS and batteryboard behave different on HPI 

### ISSUE THREAD

**Issue by MFvandenBos** [DelfiSpace/HPI_FlightSoftware#6]
There is a number of odd problems when I take fully functional EPS + batteryboard and put it on the HPI: 

battery board 1 + EPS (newest software), on battery:  
![image](https://user-images.githubusercontent.com/35063713/72601892-96c86280-3916-11ea-9764-68b5df8c2c17.png)

Now I put the same 2 board on the HPI and odly the battery INA is not working, also, the charge of the LTC changed and the temperature of the LTC changed. Even more strange is that although the INA does not work, it is still giving the correct voltage.
![image](https://user-images.githubusercontent.com/35063713/72602035-e27b0c00-3916-11ea-9f66-c2d996e0f692.png)

I think there is a communication error. Next I will try powering the board from the battery instead of the HPI. I have to discharge the battery such that its voltage is low enough.

**Comment by StefanoSperetta** [comment]
Can you check if this is the only affected telemetry? It seems there might be a communication ion tuerror..might be an option to put a print on the console in the EPS to see which value the EPS is generating and which value is received...

I guess you are using the same EPS on the HPI and afterwards on the EGSE, right?

Is the LTC status bit OK or error?

**Comment by MFvandenBos** [comment]
I have here 2 EPSes, 2 battery boards, I tried all combinations, with the same result. 

As far as the other telemetry, I think the int voltage is a bit low: 
![image](https://user-images.githubusercontent.com/35063713/72604543-620ada00-391b-11ea-9955-2a3efbebbb2c.png)

Also the B4 INA is giving an error, 

![image](https://user-images.githubusercontent.com/35063713/72604638-98e0f000-391b-11ea-9d64-1b2217f4c9a5.png)
 but I am able to turn on bus 4 and then the INA  is giving accurate results.

**Comment by MFvandenBos** [comment]
This is the setup as is now. But i also tried putting the batteryboard on the batteryboard space on the HPI, but that does not make a difference. 

![IMG_20200117_104344625](https://user-images.githubusercontent.com/35063713/72604825-eeb59800-391b-11ea-8c4d-e92a4858ed42.jpg)

**Comment by StefanoSperetta** [comment]
So, just to recap: the INA on bus4 gives an error (in the bit status) but the current and the voltage are correct? And this happens only on the HPI and not on the EGSE?
(beside the battery charge/voltage)

**Comment by MFvandenBos** [comment]
yes

**Comment by MFvandenBos** [comment]
When the EPS on the HPI is powered from the battery there is no difference from when the batteryboard receives power from the HPI.

**Comment by StefanoSperetta** [comment]
On the HPI, I disabled the CRC in the PQ9 frame (it was complex to calculate it, given the specific sw) but I think I will re-enable it to make sure we can test it on Monday... it might be that we loose bytes... do you see errors in the console (on the webpage)?

**Comment by MFvandenBos** [comment]
I do not see any errors on the console.

**Comment by StefanoSperetta** [comment]
OK, I will re-add the CRC calculation and (hopefully) we will be able to see the problem...

**Comment by MFvandenBos** [comment]
mSB of a byte is set to 0 when it should be one: 

couple of examples: 


setting BattCurrent
eps sets: FFE7		= two's complement -24			
we get 7F6F = 01111111 01101111

setting B4 ina status? 
eps sets = F0		telemetry[8] &0x80 = 1 , but on PC it is 0

setting batt ina status?
eps sets C3 = 11000011 
but that byte on telemetry = 01000011

setting BattTemperature
0DE = 222 , we get 94 = 5E
DE = 11011110
5E = 01011110

(this only happens sometimes)
setting SPYp current?
00						telemetry[34] and telemetry[35] = 00
but we get 0x7F7F

**Comment by StefanoSperetta** [comment]
CRC to be added still, hopefully coming up soon but I guess the error was caused by the MSB of each byte being messed up, @MFvandenBos ?

**Comment by MFvandenBos** [comment]
This issue has been solved. Test Results for EPS are the same when connected through HPI for update: 
97246f25f740f461c7b37e0254da92225618da85

There is one remaining difference which is related to (occasional timeouts on communication): 
https://github.com/DelfiSpace/HPI_FlightSoftware/issues/7

Therefore I am closing this issue.
