### ISSUE TITLE
Post transmission delay, bus contention 

### ISSUE THREAD

**Issue by MFvandenBos** [DelfiSpace/HPI_FlightSoftware#7]
If the computer detects the transmission, it immediately sends the next command. If the micro controller is still in the post transmission delay there is a bus contention. 

We need to profile the bus.

**Comment by StefanoSperetta** [comment]
The issue was apparently solved before in PQ9Bus and HPI/HWInterface but keeps popping up again.
It would be best to profile how long the loop takes using an oscilloscope and try with different baudrate settings to come up with a more universal solution...

**Comment by MFvandenBos** [comment]
Changed delay profile on Communication buses for now.
https://github.com/DelfiSpace/HPI_FlightSoftware/commit/ff095c16a9ffffd2a6319781460e33e894d0ca97
https://github.com/DelfiSpace/PQ9Bus/commit/db569801c7673b860c579ea5cf39c28f6772f005

**Comment by MFvandenBos** [comment]
@CasperBroekhuizen

**Comment by MFvandenBos** [comment]
Pinging HPI 10000 times, with new firmware has no timeouts. (ping serial prints disabled)firmware: 97246f25f740f461c7b37e0254da92225618da85

Pinging EPS 10000 times through HPI as 2 timeouts.  (EPS ping serial prints disabled as well)

Pinging EPS 10000 times direcly on EGSE has no time outs

**Comment by StefanoSperetta** [comment]
OK, I think we are in a good state. Practically I do not expect problems to happen in orbit with these numbers.
What will have to happen is probably a general optimization of the interrupts: the HPI RS485 interrupt (but it also applies to I2C and PQ9Bus interrupts) are too big. I would close this issue and open a new one with a much longer deadline to restructure the interrupts moving all computations to a background process and leave the interrupt to only move data to memory (when DMA cannot be used).

This should also solve the problem with low-power modes.
