### ISSUE TITLE
Put limit on the size byte size

### ISSUE THREAD

**Issue by MFvandenBos** [DelfiSpace/HPI_FlightSoftware#8]
There is no limit on the byte size.  If fr example 7E FF FF is received the receiver will not recover except through a watchdog reset.

**Comment by MFvandenBos** [comment]
RS485.cpp

**Comment by StefanoSperetta** [comment]
Implemented in ee16f40889d387dd469f1ea442233484d68674b6, please check it.

**Comment by StefanoSperetta** [comment]
I assume this has been checked, based on the test results in https://github.com/DelfiSpace/HPI_FlightSoftware/issues/7
